-- DDL CHANGES 
-- CREATED BY : MILAN KAMBOYA
-- CREATED DATE : 09/10/2016


CREATE DATABASE  IF NOT EXISTS `CALENDARAPPDB`;
USE `CALENDARAPPDB`;

-- CHANGES TO ADD TWO NEW COLUMNS IN USER_MASTER TABLE
ALTER TABLE CALENDARAPPDB.USER_MASTER ADD COLUMN EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE CALENDARAPPDB.USER_MASTER ADD COLUMN ISISOLATED VARCHAR(2) NOT NULL DEFAULT 'N';


LOCK TABLES `USER_MASTER` WRITE;

-- UPDATE SAMPLE DATA AFTER ADDING NEW COLUMNS
UPDATE CALENDARAPPDB.USER_MASTER SET EMAIL='TESTEMAIL@GMAIL.COM' WHERE ID='1';

COMMIT;

UNLOCK TABLES;

